"""Theme and design system package for Local CodeAgent."""

from learn_smolagents.ui.theme.formatting import (
    format_agent_turn_header,
    format_error_header,
    format_thought_header,
    format_timeline_body,
    format_timestamp,
    format_tool_header,
    format_user_turn_header,
)
from learn_smolagents.ui.theme.styles import (
    CODE_THEME,
    MARKDOWN_THEME,
    WarmGruvboxStyle,
)
from learn_smolagents.ui.theme.tokens import (
    ACCENT,
    ACCENT_ROSE,
    ACCENT_SOFT,
    ACCENT_WARM,
    BACKGROUND,
    BG_BASE,
    BG_BORDER,
    BG_BORDER_FOCUS,
    BG_HOVER,
    BG_OVERLAY,
    BG_SURFACE,
    COLOR_DANGER,
    COLOR_INFO,
    COLOR_SUCCESS,
    COLOR_WARNING,
    FG_FAINT,
    FG_MUTED,
    FG_PRIMARY,
    FOREGROUND,
    MUTED,
)

__all__ = [
    "ACCENT",
    "ACCENT_ROSE",
    "ACCENT_SOFT",
    "ACCENT_WARM",
    "BACKGROUND",
    "BG_BASE",
    "BG_BORDER",
    "BG_BORDER_FOCUS",
    "BG_HOVER",
    "BG_OVERLAY",
    "BG_SURFACE",
    "CODE_THEME",
    "COLOR_DANGER",
    "COLOR_INFO",
    "COLOR_SUCCESS",
    "COLOR_WARNING",
    "FG_FAINT",
    "FG_MUTED",
    "FG_PRIMARY",
    "FOREGROUND",
    "MARKDOWN_THEME",
    "MUTED",
    "WarmGruvboxStyle",
    "format_agent_turn_header",
    "format_error_header",
    "format_thought_header",
    "format_timeline_body",
    "format_timestamp",
    "format_tool_header",
    "format_user_turn_header",
]
